# Keras

Keras 是一个用于构建和训练深度学习模型的高阶 API。它可用于快速设计原型、高级研究和生产。

keras的3个优点：
方便用户使用、模块化和可组合、易于扩展


##  1.导入tf.keras
tensorflow2推荐使用keras构建网络，常见的神经网络都包含在keras.layer中(最新的tf.keras的版本可能和keras不同)

In [1]:
import tensorflow as tf
from tensorflow.keras import layers
print(tf.__version__)
print(tf.keras.__version__)

2.0.0-alpha0
2.2.4-tf


## 2.构建简单模型
### 2.1模型堆叠
最常见的模型类型是层的堆叠：tf.keras.Sequential 模型

In [2]:
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

### 2.2网络配置

tf.keras.layers中网络配置：

activation：设置层的激活函数。此参数由内置函数的名称指定，或指定为可调用对象。默认情况下，系统不会应用任何激活函数。

kernel_initializer 和 bias_initializer：创建层权重（核和偏差）的初始化方案。此参数是一个名称或可调用对象，默认为 "Glorot uniform" 初始化器。

kernel_regularizer 和 bias_regularizer：应用层权重（核和偏差）的正则化方案，例如 L1 或 L2 正则化。默认情况下，系统不会应用正则化函数。

In [3]:
layers.Dense(32, activation='sigmoid')
layers.Dense(32, activation=tf.sigmoid)
layers.Dense(32, kernel_initializer='orthogonal')
layers.Dense(32, kernel_initializer=tf.keras.initializers.glorot_normal)
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l2(0.01))
layers.Dense(32, kernel_regularizer=tf.keras.regularizers.l1(0.01))

## 3.训练和评估
### 3.1设置训练流程
构建好模型后，通过调用 compile 方法配置该模型的学习流程：


In [4]:
model = tf.keras.Sequential()
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(32, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=[tf.keras.metrics.categorical_accuracy])

### 3.2输入Numpy数据

In [5]:
import numpy as np

train_x = np.random.random((1000, 72))
train_y = np.random.random((1000, 10))

val_x = np.random.random((200, 72))
val_y = np.random.random((200, 10))

model.fit(train_x, train_y, epochs=10, batch_size=100,
          validation_data=(val_x, val_y))

Train on 1000 samples, validate on 200 samples
Epoch 1/10
1000/1000 [==============================] - 0s 302us/sample - loss: 11.8430 - categorical_accuracy: 0.0940 - val_loss: 11.8829 - val_categorical_accuracy: 0.0850
Epoch 2/10
1000/1000 [==============================] - 0s 13us/sample - loss: 12.2077 - categorical_accuracy: 0.0850 - val_loss: 12.6407 - val_categorical_accuracy: 0.0850
Epoch 3/10
1000/1000 [==============================] - 0s 25us/sample - loss: 13.3500 - categorical_accuracy: 0.0940 - val_loss: 14.4725 - val_categorical_accuracy: 0.0850
Epoch 4/10
1000/1000 [==============================] - 0s 22us/sample - loss: 15.7563 - categorical_accuracy: 0.1070 - val_loss: 17.8371 - val_categorical_accuracy: 0.0850
Epoch 5/10
1000/1000 [==============================] - 0s 22us/sample - loss: 19.9573 - categorical_accuracy: 0.1000 - val_loss: 23.3407 - val_categorical_accuracy: 0.0750
Epoch 6/10
1000/1000 [==============================] - 0s 29us/sample - loss: 25.7599 

### 3.3tf.data输入数据

In [6]:
dataset = tf.data.Dataset.from_tensor_slices((train_x, train_y))
dataset = dataset.batch(32)
dataset = dataset.repeat()
val_dataset = tf.data.Dataset.from_tensor_slices((val_x, val_y))
val_dataset = val_dataset.batch(32)
val_dataset = val_dataset.repeat()

model.fit(dataset, epochs=10, steps_per_epoch=30,
          validation_data=val_dataset, validation_steps=3)

W0308 22:45:22.538554 140299441469184 training_utils.py:1353] Expected a shuffled dataset but input dataset `x` is not shuffled. Please invoke `shuffle()` on input dataset.


Epoch 1/10
30/30 [==============================] - 0s 4ms/step - loss: 120.5764 - categorical_accuracy: 0.1094 - val_loss: 167.2411 - val_categorical_accuracy: 0.0833
Epoch 2/10
30/30 [==============================] - 0s 3ms/step - loss: 208.8775 - categorical_accuracy: 0.0983 - val_loss: 272.6065 - val_categorical_accuracy: 0.1250
Epoch 3/10
30/30 [==============================] - 0s 3ms/step - loss: 323.3857 - categorical_accuracy: 0.0962 - val_loss: 401.4161 - val_categorical_accuracy: 0.0833
Epoch 4/10
30/30 [==============================] - 0s 3ms/step - loss: 457.8510 - categorical_accuracy: 0.1015 - val_loss: 546.6275 - val_categorical_accuracy: 0.0833
Epoch 5/10
30/30 [==============================] - 0s 2ms/step - loss: 609.1648 - categorical_accuracy: 0.1197 - val_loss: 712.8060 - val_categorical_accuracy: 0.0938
Epoch 6/10
30/30 [==============================] - 0s 2ms/step - loss: 780.5939 - categorical_accuracy: 0.0972 - val_loss: 891.2927 - val_categorical_accuracy:

### 3.4评估与预测

In [7]:
test_x = np.random.random((1000, 72))
test_y = np.random.random((1000, 10))
model.evaluate(test_x, test_y, batch_size=32)
test_data = tf.data.Dataset.from_tensor_slices((test_x, test_y))
test_data = test_data.batch(32).repeat()
model.evaluate(test_data, steps=30)

30/30 [==============================] - 0s 2ms/step - loss: 1434.2727 - categorical_accuracy: 0.0917


[1434.2726928710938, 0.09166667]

In [8]:
# predict
result = model.predict(test_x, batch_size=32)
print(result)

[[0.03482518 0.         0.         ... 0.         0.01383898 0.00980373]
 [0.04969706 0.         0.         ... 0.         0.01390861 0.01697475]
 [0.05528085 0.         0.         ... 0.         0.01484961 0.01221495]
 ...
 [0.02390553 0.         0.         ... 0.         0.0051297  0.01121524]
 [0.04970536 0.         0.         ... 0.         0.00756324 0.01169133]
 [0.0402186  0.         0.         ... 0.         0.00886078 0.01124491]]


## 4.构建高级模型

### 4.1函数式api
tf.keras.Sequential 模型是层的简单堆叠，无法表示任意模型。使用 Keras 函数式 API 可以构建复杂的模型拓扑，例如：

多输入模型，

多输出模型，

具有共享层的模型（同一层被调用多次），

具有非序列数据流的模型（例如，残差连接）。

**使用函数式 API 构建的模型具有以下特征：**

层实例可调用并返回张量。
输入张量和输出张量用于定义 tf.keras.Model 实例。
此模型的训练方式和 Sequential 模型一样。

In [9]:
input_x = tf.keras.Input(shape=(72,))
hidden1 = layers.Dense(32, activation='relu')(input_x)
hidden2 = layers.Dense(16, activation='relu')(hidden1)
pred = layers.Dense(10, activation='softmax')(hidden2)

model = tf.keras.Model(inputs=input_x, outputs=pred)
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=['accuracy'])
model.fit(train_x, train_y, batch_size=32, epochs=5)

Epoch 1/5
1000/1000 [==============================] - 0s 125us/sample - loss: 12.9786 - accuracy: 0.0980
Epoch 2/5
1000/1000 [==============================] - 0s 58us/sample - loss: 19.5004 - accuracy: 0.1060
Epoch 3/5
1000/1000 [==============================] - 0s 44us/sample - loss: 34.5295 - accuracy: 0.1040
Epoch 4/5
1000/1000 [==============================] - 0s 60us/sample - loss: 65.7156 - accuracy: 0.0950
Epoch 5/5
1000/1000 [==============================] - 0s 51us/sample - loss: 118.1614 - accuracy: 0.1190


## 4.2模型子类化
通过对 tf.keras.Model 进行子类化并定义您自己的前向传播来构建完全可自定义的模型。在 __init__ 方法中创建层并将它们设置为类实例的属性。在 call 方法中定义前向传播

In [10]:
class MyModel(tf.keras.Model):
    def __init__(self, num_classes=10):
        super(MyModel, self).__init__(name='my_model')
        self.num_classes = num_classes
        self.layer1 = layers.Dense(32, activation='relu')
        self.layer2 = layers.Dense(num_classes, activation='softmax')
    def call(self, inputs):
        h1 = self.layer1(inputs)
        out = self.layer2(h1)
        return out
    
    def compute_output_shape(self, input_shape):
        shape = tf.TensorShape(input_shape).as_list()
        shape[-1] = self.num_classes
        return tf.TensorShape(shape)

model = MyModel(num_classes=10)
model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=['accuracy'])

model.fit(train_x, train_y, batch_size=16, epochs=5)

Epoch 1/5
1000/1000 [==============================] - 0s 159us/sample - loss: 14.8053 - accuracy: 0.0990
Epoch 2/5
1000/1000 [==============================] - 0s 95us/sample - loss: 22.0737 - accuracy: 0.0960
Epoch 3/5
1000/1000 [==============================] - 0s 62us/sample - loss: 28.5564 - accuracy: 0.0990
Epoch 4/5
1000/1000 [==============================] - 0s 84us/sample - loss: 33.0303 - accuracy: 0.1010
Epoch 5/5
1000/1000 [==============================] - 0s 72us/sample - loss: 36.4832 - accuracy: 0.1040


## 4.3自定义层
通过对 tf.keras.layers.Layer 进行子类化并实现以下方法来创建自定义层：

build：创建层的权重。使用 add_weight 方法添加权重。

call：定义前向传播。

compute_output_shape：指定在给定输入形状的情况下如何计算层的输出形状。
或者，可以通过实现 get_config 方法和 from_config 类方法序列化层。


In [11]:
class MyLayer(layers.Layer):
    def __init__(self, output_dim, **kwargs):
        self.output_dim = output_dim
        super(MyLayer, self).__init__(**kwargs)
    
    def build(self, input_shape):
        shape = tf.TensorShape((input_shape[1], self.output_dim))
        self.kernel = self.add_weight(name='kernel1', shape=shape,
                                   initializer='uniform', trainable=True)
        super(MyLayer, self).build(input_shape)
    
    def call(self, inputs):
        return tf.matmul(inputs, self.kernel)

    def compute_output_shape(self, input_shape):
        shape = tf.TensorShape(input_shape).as_list()
        shape[-1] = self.output_dim
        return tf.TensorShape(shape)

    def get_config(self):
        base_config = super(MyLayer, self).get_config()
        base_config['output_dim'] = self.output_dim
        return base_config

    @classmethod
    def from_config(cls, config):
        return cls(**config)
    
model = tf.keras.Sequential(
[
    MyLayer(10),
    layers.Activation('softmax')
])


model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
             loss=tf.keras.losses.categorical_crossentropy,
             metrics=['accuracy'])

model.fit(train_x, train_y, batch_size=16, epochs=5)

        

Epoch 1/5
1000/1000 [==============================] - 0s 127us/sample - loss: 11.6270 - accuracy: 0.1130
Epoch 2/5
1000/1000 [==============================] - 0s 73us/sample - loss: 11.6259 - accuracy: 0.1130
Epoch 3/5
1000/1000 [==============================] - 0s 72us/sample - loss: 11.6243 - accuracy: 0.1080
Epoch 4/5
1000/1000 [==============================] - 0s 115us/sample - loss: 11.6234 - accuracy: 0.1070
Epoch 5/5
1000/1000 [==============================] - 0s 85us/sample - loss: 11.6219 - accuracy: 0.1070


## 4.3回调

In [12]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(patience=2, monitor='val_loss'),
    tf.keras.callbacks.TensorBoard(log_dir='./logs')
]
model.fit(train_x, train_y, batch_size=16, epochs=5,
         callbacks=callbacks, validation_data=(val_x, val_y))

Train on 1000 samples, validate on 200 samples
Epoch 1/5
1000/1000 [==============================] - 0s 214us/sample - loss: 11.6202 - accuracy: 0.1050 - val_loss: 11.5276 - val_accuracy: 0.0950
Epoch 2/5
1000/1000 [==============================] - 0s 106us/sample - loss: 11.6219 - accuracy: 0.1080 - val_loss: 11.5256 - val_accuracy: 0.1050
Epoch 3/5
1000/1000 [==============================] - 0s 77us/sample - loss: 11.6234 - accuracy: 0.1020 - val_loss: 11.5226 - val_accuracy: 0.1100
Epoch 4/5
1000/1000 [==============================] - 0s 94us/sample - loss: 11.6213 - accuracy: 0.0980 - val_loss: 11.5266 - val_accuracy: 0.1050
Epoch 5/5
1000/1000 [==============================] - 0s 88us/sample - loss: 11.6211 - accuracy: 0.1010 - val_loss: 11.5253 - val_accuracy: 0.1150


## 5保持和恢复
### 5.1权重保存

In [13]:
model = tf.keras.Sequential([
layers.Dense(64, activation='relu'),
layers.Dense(10, activation='softmax')])

model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.save_weights('./weights/model')
model.load_weights('./weights/model')
model.save_weights('./model.h5')
model.load_weights('./model.h5')

### 5.2保存网络结构

In [14]:
# 序列化成json
import json
import pprint
json_str = model.to_json()
pprint.pprint(json.loads(json_str))
fresh_model = tf.keras.models.model_from_json(json_str)

{'backend': 'tensorflow',
 'class_name': 'Sequential',
 'config': {'layers': [{'class_name': 'Dense',
                        'config': {'activation': 'relu',
                                   'activity_regularizer': None,
                                   'bias_constraint': None,
                                   'bias_initializer': {'class_name': 'Zeros',
                                                        'config': {}},
                                   'bias_regularizer': None,
                                   'dtype': None,
                                   'kernel_constraint': None,
                                   'kernel_initializer': {'class_name': 'GlorotUniform',
                                                          'config': {'seed': None}},
                                   'kernel_regularizer': None,
                                   'name': 'dense_17',
                                   'trainable': True,
                                   'units': 64,

In [15]:
# 保持为yaml格式  #需要提前安装pyyaml

yaml_str = model.to_yaml()
print(yaml_str)
fresh_model = tf.keras.models.model_from_yaml(yaml_str)

backend: tensorflow
class_name: Sequential
config:
  layers:
  - class_name: Dense
    config:
      activation: relu
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dtype: null
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config: {seed: null}
      kernel_regularizer: null
      name: dense_17
      trainable: true
      units: 64
      use_bias: true
  - class_name: Dense
    config:
      activation: softmax
      activity_regularizer: null
      bias_constraint: null
      bias_initializer:
        class_name: Zeros
        config: {}
      bias_regularizer: null
      dtype: null
      kernel_constraint: null
      kernel_initializer:
        class_name: GlorotUniform
        config: {seed: null}
      kernel_regularizer: null
      name: dense_18
      trainable: true
      units: 10
      use_bias: true
  name: 

### 5.3保存整个模型


In [16]:
model = tf.keras.Sequential([
  layers.Dense(10, activation='softmax', input_shape=(72,)),
  layers.Dense(10, activation='softmax')
])
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(train_x, train_y, batch_size=32, epochs=5)
model.save('all_model.h5')
model = tf.keras.models.load_model('all_model.h5')

Epoch 1/5
1000/1000 [==============================] - 0s 131us/sample - loss: 11.6308 - accuracy: 0.1040
Epoch 2/5
1000/1000 [==============================] - 0s 40us/sample - loss: 11.6897 - accuracy: 0.1080
Epoch 3/5
1000/1000 [==============================] - 0s 55us/sample - loss: 11.7418 - accuracy: 0.1070
Epoch 4/5
1000/1000 [==============================] - 0s 43us/sample - loss: 11.7983 - accuracy: 0.1060
Epoch 5/5
1000/1000 [==============================] - 0s 47us/sample - loss: 11.8449 - accuracy: 0.0910


## 6.将keras用于Estimator
Estimator API 用于针对分布式环境训练模型。它适用于一些行业使用场景，例如用大型数据集进行分布式训练并导出模型以用于生产

In [17]:
model = tf.keras.Sequential([layers.Dense(10,activation='softmax'),
                          layers.Dense(10,activation='softmax')])

model.compile(optimizer=tf.keras.optimizers.RMSprop(0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

estimator = tf.keras.estimator.model_to_estimator(model)

W0308 22:45:28.520160 140299441469184 estimator.py:1799] Using temporary folder as model directory: /tmp/tmpzg_jzz1o
